Queries and Data
AlucardSanin/vet_clinic pull request #2
Opened 2023-02-22 23:44 UTC by AlucardSanin

Qquery and update animals table.

**Project requirements**

Add a column species of type string to your animals table. Modify your schema.sql file.
Insert the following data:
Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
Animal: Her name is Plantmon. She was born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to escape 3 times.
Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
Animal: His name is Ditto. He was born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to escape 4 times.
Remember to add these insertions to your data.sql file.

- Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
![Captura1](https://user-images.githubusercontent.com/99287916/220787876-f502cf64-71c4-4fc0-ac07-97bdefa8bb7c.JPG)

- Inside a transaction:

Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
Commit the transaction.
Verify that change was made and persists after commit.

![Captura2](https://user-images.githubusercontent.com/99287916/220787990-b90dad2c-5bd9-461d-a2ae-c9fe5d45ac97.JPG)

- Now, take a deep breath and... Inside a transaction delete all records in the animals table, then roll back the transaction.

After the rollback verify if all records in the animals table still exists. After that, you can start breathing as usual ;)

![Captura3](https://user-images.githubusercontent.com/99287916/220788072-48a19a2b-169d-403a-ae1b-fb0bc21fc619.JPG)

- Inside a transaction:

Delete all animals born after Jan 1st, 2022.
Create a savepoint for the transaction.

![Captura4](https://user-images.githubusercontent.com/99287916/220788156-4f5a1ec5-4d17-4b33-83e4-96074bb1eb21.JPG)

- Update all animals' weight to be their weight multiplied by -1.

Rollback to the savepoint
Update all animals' weights that are negative to be their weight multiplied by -1.
Commit transaction

![Captura5](https://user-images.githubusercontent.com/99287916/220788233-5490e131-3f5b-4b27-8b8e-21b73750ce30.JPG)

Write queries to answer the following questions:

- How many animals are there?
![Captura8](https://user-images.githubusercontent.com/99287916/220788749-7c9eb26a-419e-4301-a5fd-257dbbf15e86.JPG)

- How many animals have never tried to escape?
- What is the average weight of animals?
- Who escapes the most, neutered or not neutered animals?

![Captura6](https://user-images.githubusercontent.com/99287916/220788821-e633c94c-2895-4b82-8e8d-bdd4de6f81dd.JPG)

- What is the minimum and maximum weight of each type of animal?
- What is the average number of escape attempts per animal type of those born between 1990 and 2000?

![Captura7](https://user-images.githubusercontent.com/99287916/220788902-b6869a84-9d9c-4010-ba4b-547c24f98ae7.JPG)

2023-02-22 23:55 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @AlucardSanin , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [x] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-22 23:55 UTC, MaganaAsiati commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN DATE '1990-01-01' AND '2000-01-01' GROUP BY species;
#### queries.sql

1. Students should create queries to answer the following questions in transactions. Please note: if students find another way that presented in the example that also works, it is fine!
   * Inside a transaction:
     * `UPDATE` the animals table by setting the species column to unspecified, then roll back the change (\*\*for this step students are explicitly asked to verify that change was made and rollbacked, so make sure that they included all steps as in the example below \*\*).

     ```sql
        BEGIN; -- start transaction
     
        UPDATE animals
        SET species = 'unspecified'; -- make change
     
        SELECT species from animals; -- verify that change was made
        ROLLBACK;
     
        SELECT species from animals; -- verify that change was undone
     ```
   * Inside a transaction:
     * `UPDATE` the animals table by setting the species column to digimon for all animals that have a name ending in mon.
     * `UPDATE` the animals table by setting the species column to pokemon for all animals that don't have species already set.
     * Commit the transaction.

     ```sql
        BEGIN;
        UPDATE animals SET species = 'digimon' WHERE name LIKE '%mon'; 
        UPDATE animals SET species = 'pokemon' WHERE species IS NULL; 
     
        SELECT species from animals; -- verify that change was made
        COMMIT;
        SELECT species from animals; -- verify that change persists after commit
     ```
   * Inside a transaction delete all records in the animals table, then roll back the transaction.

     ```sql
        BEGIN;
     
        DELETE FROM animals WHERE ;
        SELECT COUNT(*) FROM ANIMALS;
     
        ROLLBACK;
        SELECT COUNT(*) FROM ANIMALS;
     
     ```
   * Inside a transaction:
     * `DELETE` all animals born after Jan 1st, 2022
     * Create a savepoint for the transaction
     * `UPDATE` all animals' weight to be their weight multiplied by -1.
     * Rollback to the savepoint
     * `UPDATE` all animals' weights that are negative to be their weight multiplied by -1.
     * Commit transaction

     ```sql
         BEGIN;
     
         DELETE FROM animals WHERE  date_of_birth > '2022/01/01' ;
         SAVEPOINT SP1;
     
         UPDATE animals SET weight_kg = weight_kg * -1; 
         ROLLBACK TO SP1;
         UPDATE animals SET weight_kg = weight_kg * -1 WHERE weight_kg < 0; 
     
         COMMIT;
     ```

2023-02-23 00:11 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @AlucardSanin,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-23 00:12 UTC, merged

2023-03-28 16:53 UTC, Davidosky007 reviewed
Hi @AlucardSanin 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Proper use of Gitflow 👍 
* Well written PR description 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._